version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - gomoddirectives
    - lll
    - nlreturn
    - noinlineerr
    - perfsprint
    - prealloc
    - testpackage
    - thelper
    - unparam
    - wsl
    - wsl_v5
  settings:
    mnd:
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
    revive:
      rules:
        - name: package-comments
          disabled: true
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    varnamelen:
      ignore-names:
        - a
        - b
        - db
        - ev
        - id
        - ok
        - tc
        - tx

run:
  concurrency: 4
  timeout: 2m
